version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_otpapp
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    hostname: otpapp-redis
    container_name: otpapp-redis
    depends_on:
      - postgres
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass bBMUvLtS8KYzxuEXc0Mkj34c4Ph7eGOxMggCtictqSw0KP09

volumes:
  postgres_data:
